USE master
GO
DROP  DATABASE MI_HUERTA
GO
CREATE DATABASE MI_HUERTA;
GO
USE MI_HUERTA;
GO
--Esta base de datos se utilizara  para la aplicacion desarrollada en AndroidStudio denominada HUERTA la cual 
--sera la base de la aplicacion para llevar a cabo un control minusioso de la huerta tanto trabajadores, 
--control de cortes, control de actividades, de bodega, ingresos y egresos.


CREATE TABLE BIBLEOTECA_TRABAJO --EN ESTA TABLA SE ENCONTRARA TODOS LOS TRABAJOS QUE SE PUEDEN REALIZAR EN UNA HUERTA CON SU DESCRIPCION 
(
ID_TRABAJO TINYINT NOT NULL,-- IDENTIFICADOR DE TRABAJO
NOMBRE VARCHAR (45) NOT NULL, --NOMBRE PARA IDENTIFICAR EL TRABAJO 
COSTO  MONEY NOT NULL,-- LO QUE SE LE PAGARA A CADA TRABAJADOR  POR JORNADA O TAREA
DESCRIPCION VARCHAR (150) NOT NULL, -- AQUI SE ESTABLECE LO QUE SE DEBE DE HACER PARA EL TRABAJO Y SI SE PAGARA POR JORNADA O TAREA 
CONSTRAINT  ID_TRABAJO_PK PRIMARY KEY (ID_TRABAJO)
);
GO
CREATE TABLE EMPLEADOS --EN ESTA TABLA SE LLEVARA EL REGISTRO DE TODOS LOS EMPLEADOS Y SI ESTANN ACTIVOS O NO
(
ID_EMPLEADO TINYINT NOT NULL, --IDENTIFICADOR DE EMPPLEADO 
NOMBRE VARCHAR (50) NOT NULL, --NOMBRE DEL EMPLEADO
TELEFONO VARCHAR (10),  --TELEFONO DEL EMPLEADO SI ESTE TIENE
TIPO CHAR (1) NOT NULL DEFAULT '0', --DEMUESTRA EL TIPO DE TRABAJADOR "0 TRABAJADOR POR DIA O 1 SI ES DE AREA"
ESTADO_ACTIVO  CHAR (1) DEFAULT '1', --DEMOSTRARA SI EL TRABAJADOR ESTA ACTIVO O NO ESTA ACTICO "0=INACTIVO 1=ACTIVO"
CONSTRAINT ID_EMPLEADO_PK PRIMARY KEY  (ID_EMPLEADO)
);
GO
CREATE TABLE CORTES --ESTA TABLA NOS PERMITIRA LLEVAR EL CONTROL DE CADA CORTE COMO QUIEN LO HIZO CUANTO SALIO ETC.
(
ID_CORTADOR  TINYINT NOT NULL,-- IDENTIFICADOR DEL CORTADOR
TELEFNO VARCHAR (10) NOT NULL, --NUMERO DEL CORTADOR 
CORTADOR VARCHAR NOT NULL,--NOMBRE DEL CORTADOR 
CONSTRAINT  ID_CORTADOR_PK PRIMARY KEY (ID_CORTADOR)
);
GO
CREATE TABLE VUELOS --PERMITIRA LLEVAR EL CONTRO DEL LAS FUMIGACIONES
(
ID_FUMIGADORES TINYINT NOT NULL, --IDENTIFICADOR DE FUMIGADORES
NOMBRE VARCHAR (50) NOT NULL,-- NOMBRE DE LA EMPRESA FUMIGADORA
PRECIO MONEY NOT NULL, -- EL PRECIO POR CADA VUELO
TELEFONO VARCHAR (10) NOT NULL,--NUMERO DE TELEFONO DE LA EMPRESA FUMIGADORA
CONSTRAINT ID_FUMIGADORES_PK PRIMARY KEY (ID_FUMIGADORES)
);
GO
CREATE TABLE BODEGA -- PERMITE LLEVAR EL CONTROL DE  LO QUE SE TIENE EN BODEGA
(
ID_PRODUCTO TINYINT NOT NULL,--IDENTIFICADOR DEL PRODUCTO
NOMBRE VARCHAR (50) NOT NULL,-- NOMBRE DEL PRODUCTO
S_MIN TINYINT NOT NULL,--CANTIDAD MINIMA DE PRODUCTO EN BODEGA
CANTIDAD INT NOT NULL,-- CUANTO HAY  EN BODEGA
DESCRIPCION VARCHAR (200) NOT NULL,--  DETALLE DEL PRODUCTTO COMO EL NOMBRE DE LA UNIDAD ROLLO, PAQUETE, ETC 
CONSTRAINT ID_PRODUCTO_PK PRIMARY KEY (ID_PRODUCTO)
);
GO
CREATE TABLE HUERTA --ESTA TABLA ES LA ENCARGADA DE SEPARAR CADA UNA DE LAS HUERTAS PARA LLEVAR REPORTES DE LAS MISMAS POR SEPARADO
(
ID_HUERTA  TINYINT NOT NULL,--INDENTIFICADOR DE LA HUERTA
NOMBRE_HUERTA  VARCHAR (45) NOT NULL,--NOMBRE POR EL CUAL LA HUERTA ES LLAMADA
EXTENCION TINYINT NOT NULL,--EXTENCION DE LA HUERTA EXPRESADA EN HECTAREAS
EGRESOS MONEY NOT NULL, --CUANTO HA SALIDO DE LA HUERTA
INGRESOS MONEY NOT NULL, --CUANTO HA INGRESADO NORMALMENTE POR LOSCORTES
PROPETARIO VARCHAR (50) NOT NULL,--NOMBRE DEL DUEÑO DE LA HUERTA
CAPATAZ VARCHAR  (50) NOT NULL,--NOMBRE DEL ENCARGADO DE LA HUERTA
CONSTRAINT  ID_HUERTA_PK  PRIMARY KEY (ID_HUERTA)
);
GO
CREATE TABLE DETALLE_CORTE --NOS PERMITIRA SABER LOS DETALLES DE LOS CORTES 
(
ID_CORTE TINYINT NOT NULL, --IDENTIFICADOR DE CORTE
FECHA_CORTE  DATE NOT NULL, -- FECHA EN QUE SE REALIZO EL CORTE 
CANTIDAD INT NOT NULL, --CANTIDAD EN KILOGRAMOS
PRECIO MONEY NOT NULL,--PRECIO AL QUE FUE VENDIDO
DESCUENTO MONEY NOT NULL, --DESCUENTO AL TOTAL POR GASTOS COMO CORTADOR CERVEZAS ETC...
TOTAL MONEY NOT NULL, --TOTAL RESIVIDO DEL CORTE 
CORTADOR TINYINT NOT NULL,-- SABER QUIEN CORTO
HUERTA TINYINT NOT NULL, --A QUE HUERTA SE CORTO
CONSTRAINT ID_CORTE_PK PRIMARY KEY (ID_CORTE),
CONSTRAINT ID_CORTADOR_FK FOREIGN KEY (CORTADOR) REFERENCES CORTES (ID_CORTADOR),
CONSTRAINT ID_HUERTA_FK FOREIGN KEY (HUERTA) REFERENCES  HUERTA (ID_HUERTA)
);
/*GO
CREATE TABLE DETALLE_TRABAJADORES --ESTA TABLA NOS PERMITIRA QUE SABER QUE TRABAJADOR TRABAJO EN UNA FECHA Y QUE HIZO
(
TRABAJADORES TINYINT NOT NULL, --LLAVE PRIMARIA
EMPLEADO TINYINT NOT NULL, --LLAVE FORANEA PRA SABER QUE EMPLEADO TRABAJO
FECHA DATE NOT NULL,--NOS PERMITE SABER EN QUE FECHA TRABAJO
HUERTA TINYINT NOT NULL,--PERMITIRA SABER QUE HUERTA TRABAJO
NOTA VARCHAR (200) -- DE SER INISPENSABLE NOS PERMITE  SABER CUALQUIER PERCANSE OCURRIDO EN EL TRABAJO
CONSTRAINT ID_TRABAJADORES_PK PRIMARY KEY (TRABAJADORES)--LLAVE PRINCIPAL CONCATENADA
CONSTRAINT EMPLEADO_FK FOREIGN KEY (EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
CONSTRAINT HUERTA_FK_TRABAJADORES FOREIGN KEY (HUERTA ) REFERENCES HUERTA (ID_HUERTA)
);*/
GO
CREATE TABLE DETALLE_VUELOS --ESTA TABLA NOS PERMITIRA VER LOS DETALLES DE LOS VUELOS
(
ID_VUELO TINYINT NOT NULL, --IDENTIFICADOR DEL VUELO
HUERTA TINYINT NOT NULL,--IDENTIFICADOR DE LA HUERTA
FUMIGADOR TINYINT NOT NULL,--IDENTIFICADOR DEL FUMIGADOR
ESTADO  CHAR (1) NOT NULL DEFAULT '0' ,-- SI EL ESTADO ES 0 EL VUELO SE DEBE SI ES 1 YA SE PAGO
FECHA DATE NOT NULL,-- FECHHA QUE SE REALIZO EL VUELO
PRODUCTO  VARCHAR (25) NOT NULL,--PRODUCTO QUE FUE APLICADO
TOTAL_VUELO MONEY NOT NULL,--COSTO DEL VUELO
TOTAL_PRODUCTO MONEY NOT NULL,--COSTO DEL PRODUCTO
TOTAL_BRUTO MONEY NOT NULL,--TOTAL BRUTO
CONSTRAINT ID_VUELO_PK PRIMARY KEY (ID_VUELO),
CONSTRAINT HUERTA_FK_VUELOS FOREIGN  KEY (HUERTA) REFERENCES HUERTA (ID_HUERTA),
CONSTRAINT FUMIGADOR_FK FOREIGN KEY (FUMIGADOR) REFERENCES VUELOS(ID_FUMIGADORES)
);
GO
CREATE TABLE DETALLE_BODEGA --ESTA TABLA NOS PERMITIRA LLEVAR EL  CONTROL DE LA BODEGA.
(
ID_REFERENCIA TINYINT NOT NULL,--REFERENCIA 
PRODUCTO TINYINT NOT NULL, --IDENTIFICADOR DE PRODUCTO
HUERTA TINYINT NOT NULL, --IDENTIFICADOR DE HUERTA
COSTO MONEY NOT NULL, --COSTO DE PPRODUCTO
FECHA DATE NOT NULL-- FECHA DE ACTIVIDAD 
CONSTRAINT ID_REFERENCIA_PK PRIMARY KEY (ID_REFERENCIA),
CONSTRAINT HUERTA_FK_BODEGA FOREIGN  KEY (HUERTA) REFERENCES HUERTA(ID_HUERTA),
CONSTRAINT PRODUCTO_FK FOREIGN KEY (PRODUCTO) REFERENCES BODEGA(ID_PRODUCTO)
);
GO
CREATE TABLE DETALLE_EMPLEADOS_DIA--DETALLE ENTRE EMPLEADO Y TRABAJO
(
ID_DETALLE TINYINT NOT NULL, --IDENTIFICADOR DE DETALLE
ID_EMPLEADO TINYINT NOT NULL, --IDENTIFICAR EMPLEADO
ID_TRABAJO TINYINT NOT NULL, -- IDENTIFICAR TRABAJO A REALIZAR
FECHA DATE NOT NULL,--NOS PERMITE SABER EN QUE FECHA TRABAJO
HUERTA TINYINT NOT NULL,--PERMITIRA SABER QUE HUERTA TRABAJO
NOTA VARCHAR (200) -- DE SER INISPENSABLE NOS PERMITE  SABER CUALQUIER PERCANSE OCURRIDO EN EL TRABAJO
CONSTRAINT ID_DETALLE_PK PRIMARY KEY (ID_DETALLE),
CONSTRAINT ID_EMPLEADO_FK_DIA FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
CONSTRAINT ID_TRABAJO_FK_DIA FOREIGN KEY (ID_TRABAJO) REFERENCES BIBLEOTECA_TRABAJO (ID_TRABAJO),
CONSTRAINT HUERTA_FK_DIA FOREIGN KEY (HUERTA ) REFERENCES HUERTA (ID_HUERTA)
);
GO
CREATE TABLE DETALLE_EMPLEADOS_AREA
(
ID_AREA TINYINT NOT NULL,-- IDENTIFICAR AREAS
ID_EMPLEADO TINYINT NOT NULL,--IDENTIFICAR EMPLEADO
TOTAL_HECTAREAS TINYINT NOT NULL,--HETARIAS A  CARGO DE UN TRABAJADOR
SALARIO_HECTAREA MONEY NOT NULL, --SALARIO POR HECTAREA
FECHA DATE NOT NULL,--NOS PERMITE SABER EN QUE FECHA TRABAJO
HUERTA TINYINT NOT NULL,--PERMITIRA SABER QUE HUERTA TRABAJO
NOTA VARCHAR (200) -- DE SER INISPENSABLE NOS PERMITE  SABER CUALQUIER PERCANSE OCURRIDO EN EL TRABAJO
CONSTRAINT ID_AREA_PK PRIMARY KEY (ID_AREA),
CONSTRAINT ID_EMPLEADO_FK_AREA FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
CONSTRAINT HUERTA_FK_AREA FOREIGN KEY (HUERTA ) REFERENCES HUERTA (ID_HUERTA)
);













----------------------------------------------============================================================-------------------------------------
----------------------------------------------===========MODIFICACIONES A LA BASE DE DATOS================-------------------------------------
----------------------------------------------============================================================-------------------------------------
GO
ALTER TABLE DETALLE_EMPLEADOS_AREA ADD CINTILLA_SEMANA   SMALLINT NOT NULL;--PERMITE LLEVAR EL CONTROL DE RACIMOS POR SEMANA
